name: Test, Build, and Publish Components

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: Build
      run: |
        npm ci --legacy-peer-deps
        # will be built because of the respective build script.

    - name: Run tests
      run: npm test

    - name: Publish to npm
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}